import{S as m,a as p,i as n}from"./assets/vendor-DEZpR2tN.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&o(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const h=document.querySelector(".gallery"),u=document.querySelector(".loader");function y(a){const r=a.map(({webformatURL:s,largeImageURL:o,tags:e,likes:t,views:i,comments:d,downloads:f})=>`<li class="gallery-item"><a href="${o}">
            <img class="gallery-image" src="${s}" alt="${e}" />
            <div class='item-footer'>
            <p><b>likes</b> ${t}</p>
            <p><b>views</b> ${i}</p>
            <p><b>comments</b> ${d}</p>
            <p><b>downloads</b> ${f}</p>
            </div>
        </a>
       
        </li>`).join("");h.innerHTML=r,P.refresh()}function g(){u.classList.remove("hidden-loader")}function b(){u.classList.add("hidden-loader")}const P=new m(".gallery a",{}),L="49602919-aeba24ff5374aa13ccf20c3b1",$="https://pixabay.com/api/",c={image_type:"photo",orientation:"horizontal",safesearch:!0};function A(a){return p.get(`${$}?key=${L}&q=${a}&image_type=${c.image_type}&orientation=${c.orientation}&safesearch=${c.safesearch}`).then(r=>r.data).catch(r=>{console.error("Error fetching data from Pixabay:",r)})}const l=document.querySelector(".form");l.addEventListener("submit",a=>{a.preventDefault();const r=l.elements["search-text"].value;if(r===""){n.error({message:"Please enter a search query!",position:"topCenter",timeout:3e3});return}g(),A(r).then(o=>{if(o.hits.length===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topCenter",timeout:3e3});return}y(o.hits)}).catch(()=>{n.error({message:"Error fetching data from Pixabay",position:"topCenter",timeout:3e3})}).finally(()=>{b()}),l.reset()});
//# sourceMappingURL=index.js.map
